name: fullstack-web

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:3333'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit